[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:gpsd]
command=/usr/sbin/gpsd -n -D 1 -f 8N1 -s 115200 /dev/gps
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
logfile_maxbytes=0
redirect_stderr=true

[program:ntrip_client]
command=/bin/bash -c "str2str -in ntrip://10.0.4.114:2101/ENSEA -out serial://ttyAMA0:115200:8:n:1"
# command=/bin/bash -c "str2str -in ntrip://192.168.2.2:2101/ENSEA -out serial://ttyAMA0:115200:8:n:1"
autostart=true
autorestart=true

[program:ros2]
command=/bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && ros2 launch gpsd_client gpsd_client-launch.py"
autostart=true
autorestart=true

[program:ros2_sbus_bridge]
command=/bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && source $HOME/ws/install/setup.bash && ros2 launch send_udp gps_sbus_launch.py"
autorestart=true
autostart=true
stdout_logfile=/dev/fd/1
logfile_maxbytes=0
redirect_stderr=true

[program:gps_loggger]
command=/bin/bash -c "sleep 10;echo script gps"
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
redirect_stderr=true
logfile_maxbytes=0