[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:gpsd]
command=/usr/sbin/gpsd -n -D 1 -f 8N1 -s 115200 /dev/gps
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
logfile_maxbytes=0
redirect_stderr=true
stdout_logfile_maxbytes = 0


[program:ntrip_client]
#command=/bin/bash -c "str2str -in ntrip://10.0.4.114:2101/ENSEA -out serial://ttyAMA0:115200:8:n:1"
command=/bin/bash -c "str2str -in ntrip://192.168.2.2:2101/ENSEA -out serial://ttyAMA0:115200:8:n:1"
autostart=true
autorestart=true

[program:ros2_gpsd_client]
command=/bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && ros2 launch gpsd_client gpsd_client-launch.py"
autostart=true
autorestart=true

[program:ros2_sbus_bridge]
command=/bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && source $HOME/ws/install/setup.bash && ros2 launch send_udp gps_sbus_launch.py"
autorestart=true
autostart=true
stdout_logfile=/dev/fd/1
logfile_maxbytes=0
redirect_stderr=true
stdout_logfile_maxbytes = 0

[program:ros2_pwm_bridge]
command=/bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && source $HOME/ws/install/setup.bash && ros2 launch send_udp gps_pwm_launch.py"
autorestart=true
autostart=true
stdout_logfile=/dev/fd/1
logfile_maxbytes=0
redirect_stderr=true
stdout_logfile_maxbytes = 0

[program:gps_loggger]
command=/bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && source $HOME/ws/install/setup.bash && ros2 launch gps_logger gps_logger-launch.py" 
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
redirect_stderr=true
logfile_maxbytes=0
stdout_logfile_maxbytes = 0