FROM ros:jazzy

ARG USERNAME=theseus
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Rename default user
ARG OLD_USERNAME=ubuntu
RUN usermod --login $USERNAME --move-home --home /home/$USERNAME $OLD_USERNAME\
    && groupmod --new-name $USERNAME $OLD_USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN apt-get update && apt-get upgrade -y
RUN apt-get update && apt-get install -y python3-pip
ENV SHELL=/bin/bash

# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************


RUN apt-get update && apt-get install -y gpsd gpsd-clients
RUN apt-get update && apt-get install -y ros-${ROS_DISTRO}-gpsd-client

RUN apt-get update && sudo apt-get install -y supervisor
RUN mkdir -p /var/log/supervisor

ENV RCUTILS_COLORIZED_OUTPUT=1
USER ${USERNAME}
RUN mkdir -p /home/${USERNAME}/ws/src

WORKDIR /home/${USERNAME}/ws
SHELL ["/bin/bash", "--login", "-c"] 

RUN grep -qF 'TAG1' $HOME/.profile || echo 'source /opt/ros/${ROS_DISTRO}/setup.bash # TAG1' >> $HOME/.profile

# File entrypoint.sh
COPY --chmod=+x <<-"EOF" /entrypoint.sh
#!/bin/bash

source /opt/ros/${ROS_DISTRO}/setup.bash
exec "$@"
EOF

# File supervisord.conf
COPY <<-"EOF" /etc/supervisor/conf.d/supervisord.conf
[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:gpsd]
command=/usr/sbin/gpsd -n -D 1 -f 8N1 -s 115200 /dev/gps
autostart=true
autorestart=true
stdout_logfile=/var/log/gpsd.log
stderr_logfile=/var/log/gpsd.err

[program:ros2]
command=/bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && ros2 launch gpsd_client gpsd_client-launch.py"
autostart=true
autorestart=true

[program:gps_loggger]
command=/bin/bash -c "sleep 10;echo script gps"
autostart=true
autorestart=true
stdout_logfile=/var/log/gps_loggger.log
redirect_stderr=true
EOF


ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

# ENTRYPOINT ["tail", "-f", "/dev/null"]
