name: Modelibot

services:
  ros_container:
    build:
      context: ../
      additional_contexts:
        source: ../modelidar
      dockerfile: .devcontainer/Dockerfile
      args:
        USERNAME: $_ROS_USER
    privileged: true
    environment:
      DISPLAY: $DISPLAY
      ROS_AUTOMATIC_DISCOVERY_RANGE: LOCALHOST
      ROS_DOMAIN_ID: "0"
      ROS_DISCOVERY_SERVER: "10.0.4.114:11811;10.0.4.101:11881;10.0.4.116:11811"
      #FASTDDS_BUILTIN_TRANSPORTs: "LARGE_DATA"
      #ROS_SUPER_CLIENT: true
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      #FASTRTPS_DEFAULT_PROFILES_FILE=/home/$_ROS_USER/fastdds_default_profiles.xml
    volumes:
      - ../:/home/$_ROS_USER/ws/src:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:cached
      - /dev/dri:/dev/dri:cached
      - ~/.Xauthority:/home/$_ROS_USER/.Xauthority
      - /dev/input:/dev/input:bind
      - /dev/ttyACM0:/dev/ttyACM0:bind
      - /run/user/1000:/run/user/1000
    network_mode: "host"
    ipc: "host"
    pid: "host"
    user: theseus
    tty: true