FROM ros:jazzy

ARG USERNAME=theseus
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Rename default user
ARG OLD_USERNAME=ubuntu
RUN usermod --login $USERNAME --move-home --home /home/$USERNAME $OLD_USERNAME\
    && groupmod --new-name $USERNAME $OLD_USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN apt-get update && apt-get upgrade -y
RUN apt-get update && apt-get install -y python3-pip
ENV SHELL=/bin/bash

# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************


RUN apt-get update && apt-get install -y gpsd gpsd-clients
RUN apt-get update && apt-get install -y ros-${ROS_DISTRO}-gpsd-client

RUN apt-get update && sudo apt-get install -y supervisor
RUN mkdir -p /var/log/supervisor

RUN apt-get update && apt-get install -y rtklib

RUN apt-get update && apt-get install -y libboost-dev


ENV RCUTILS_COLORIZED_OUTPUT=1
USER ${USERNAME}
RUN mkdir -p /home/${USERNAME}/ws/src

WORKDIR /home/${USERNAME}/ws
SHELL ["/bin/bash", "--login", "-c"] 

ADD https://github.com/jenswilly/sbus_serial.git /home/${USERNAME}/ws/src/sbus_serial

RUN source /opt/ros/${ROS_DISTRO}/setup.bash; colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-select sbus_serial

RUN --mount=type=bind,source=send_udp,target=src/send_udp \
    /bin/bash -c "source  /opt/ros/${ROS_DISTRO}/setup.bash; colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-select send_udp"

RUN grep -qF 'TAG1' $HOME/.profile || echo 'source /opt/ros/${ROS_DISTRO}/setup.bash # TAG1' >> $HOME/.profile
RUN grep -qF 'TAG2' $HOME/.profile || echo 'source $HOME/ws/install/setup.bash # TAG2' >> $HOME/.profile

# File entrypoint.sh
COPY --chmod=+x <<-"EOF" /entrypoint.sh
#!/bin/bash

source /opt/ros/${ROS_DISTRO}/setup.bash
source $HOME/ws/install/setup.bash
exec "$@"
EOF

RUN apt-get install -y python-pip && pip install supervisor-stdout

RUN sed -i 's/DEVICES=""/DEVICES="\/dev\/gps"/g' /etc/default/gpsd
RUN sed -i 's/USBAUTO="true"/USBAUTO="false"/g' /etc/default/gpsd
RUN sed -i 's/GPSD_OPTIONS=""/GPSD_OPTIONS="-n -D 1 -f 8N1 -s 115200/g' /etc/default/gpsd
RUN sed -i 's/START_DAEMON="false"/START_DAEMON="true"/g' /etc/default/gpsd

# File supervisord.conf
COPY supervisor-gpsd.conf /etc/supervisor/conf.d/supervisord.conf



ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

# ENTRYPOINT ["tail", "-f", "/dev/null"]
