name: Modelibot

services:
  ros_container:
    image: ros_modelibot
    build:
      context: ../
      additional_contexts:
        source: ../modelidar
      dockerfile: .devcontainer/Dockerfile
      args:
        USERNAME: ${_ROS_USER:?Please set an .env file with _ROS_USER}
    privileged: true
    depends_on:
      - fastdds_server
    environment:
      # DISPLAY: $DISPLAY
      ROS_AUTOMATIC_DISCOVERY_RANGE: LOCALHOST
      ROS_DOMAIN_ID: ${_ROS_DOMAIN_ID:-0}
      ROS_DISCOVERY_SERVER: $_DISCOVERY_SERVER_LIST
      #FASTDDS_BUILTIN_TRANSPORTs: "LARGE_DATA"
      ROS_SUPER_CLIENT: ${_ROS_SUPER_CLIENT:-false}
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      #FASTRTPS_DEFAULT_PROFILES_FILE=/home/$_ROS_USER/fastdds_default_profiles.xml
    volumes:
      - ../:/home/$_ROS_USER/ws/src:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:cached
      - /dev/dri:/dev/dri:cached
      - ~/.Xauthority:/home/$_ROS_USER/.Xauthority
      - /dev/input:/dev/input:bind
      - /dev:/dev:bind
      - /run/user/1000:/run/user/1000
    network_mode: "host"
    ipc: "host"
    pid: "host"
    user: $_ROS_USER
    tty: true
    command: "ros2 launch modelidar modelidar.launch.py use_mock_hardware:=true gui:=false"
  
  fastdds_server:
    image: ros_modelibot
    privileged: true
    environment:
      ROS_DOMAIN_ID: ${_ROS_DOMAIN_ID:-0}
      ROS_DISCOVERY_SERVER: $_DISCOVERY_SERVER_LIST
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    network_mode: "host"
    ipc: "host"
    pid: "host"
    user: $_ROS_USER
    tty: true
    command: /bin/bash -l -c 'fastdds discovery -i ${_SERVER_ID:?_SERVER_ID must be set in .env file}'