<?xml version="1.0"?>
<robot name="wild_thumper" xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:arg name="prefix" default="" />
  	<xacro:arg name="use_mock_hardware" default="false" />

	<xacro:property name="PI" value="3.1415926535897931" />

	<!-- Import Rviz colors -->
	<xacro:include filename="materials.xacro" />

	<link name="$(arg prefix)base_footprint">
		<visual>
			<geometry>
				<box size="0.28 0.31 0.000001"/>
			</geometry>
			<material name="wtgrey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0.1" rpy="0 0 0"/>
			<geometry>			
				<box size="0.28 0.31 0.2"/>
			</geometry>
		</collision>
	</link>

	<link name="$(arg prefix)base_link">
		<visual>
			<origin xyz="-0.00275 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://modelidar/meshes/wild_thumper_4wd.stl" />
			</geometry>
		</visual>
		<inertial>
			<origin xyz="-0.00275 0 0" rpy="0 0 0"/>
			<mass value="2.5"/>
			<inertia izz="0.014021" ixy="0.0" ixz="0.0" iyy="0.012708" iyz="0.0" ixx="0.0046875"/>
		</inertial>
	</link>

	<link name="$(arg prefix)base_imu_link">
		<visual>
			<origin xyz="-0.014319 0 0" rpy="0 0 0"/>
			<geometry>
				<!--<box size="0.041 0.028 0.002"/>-->	
				<mesh filename="package://modelidar/meshes/IMU-Support.stl" scale="0.001 0.001 0.001"/>
			</geometry>
			<material name="wtblue"/>
		</visual>
	</link>

	<link name="$(arg prefix)mounting_plate">
		<visual>
			<geometry>
				<box size="0.23 0.12 0.001"/>
			</geometry>
		</visual>
	</link>

	<link name="$(arg prefix)lidar">
		<visual>
			<geometry>
				<!--<cylinder radius="0.05207" length="0.0716"/>-->
				<mesh filename="package://modelidar/meshes/Velodyne_PartBody.stl" scale="0.001 0.001 0.001"/>
				<!--<mesh filename="package://modelidar/meshes/rplidar_a2.stl" scale="0.001 0.001 0.001"/>-->
			</geometry>
			<origin xyz="0.0 0.0 0" rpy="0 0 0"/>
			<material name="wtsilver"/>
		</visual>
	</link>

	<link name="$(arg prefix)camera_front">
		<visual>
			<geometry>
				<box size="0.016 0.044 0.02"/>
			</geometry>
			<origin xyz="${0.016/2} 0 0" rpy="0 0 0"/>
			<material name="wtpurple"/>
		</visual>
	</link>

	<joint name="$(arg prefix)base_link_joint" type="fixed">
		<parent link="$(arg prefix)base_footprint"/>
		<child link="$(arg prefix)base_link"/>
		<origin xyz="0.0 0.0 0.082" rpy="0 0 0"/>
	</joint>

	<joint name="$(arg prefix)mounting_plate_joint" type="fixed">
		<parent link="$(arg prefix)base_link"/>
		<child link="$(arg prefix)mounting_plate"/>
		<origin xyz="0.0 0.0 0.044" rpy="0 0 0"/>
	</joint>

	<joint name="$(arg prefix)imu_joint" type="fixed">
		<parent link="$(arg prefix)mounting_plate"/>
		<child link="$(arg prefix)base_imu_link"/>
		<!--<origin xyz="0.06 -0.03 0.058" rpy="0 0 0"/>-->
		<origin xyz="0 0 0.0765" rpy="0 0 0"/>
	</joint>


	<joint name="$(arg prefix)camera_front_joint" type="fixed">
		<parent link="$(arg prefix)mounting_plate"/>
		<child link="$(arg prefix)camera_front"/>
		<origin xyz="0.115 0.00 -0.012" rpy="0 0 0"/>
	</joint>
	
	<joint name="$(arg prefix)lidar_joint" type="fixed">
		<parent link="$(arg prefix)mounting_plate"/>
		<child link="$(arg prefix)lidar"/>
		<origin xyz="0.060 0.0 0" rpy="0 0 ${-110*PI/180}"/>
	</joint>

	<xacro:macro name="wheel" params="prefix pos side xyz rpy">   
		<link name="${prefix}${pos}_${side}_wheel">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://modelidar/meshes/wheel_${side}.stl" />
				</geometry>
				<material name="wtblack"/>
			</visual>
			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="0.2"/>
				<inertia ixx="0.00024" ixy="0" ixz="0" iyy="0.00036" iyz="0" izz="0.00024"/>
			</inertial>
		</link>

		<gazebo reference="${prefix}${pos}_${side}_wheel">
			<mu1 value="1.0"/>
			<mu2 value="0.2"/>
			<kp value="1000000000000.0" />
			<kd value="1.0" />
			<fdir1 value="0 1 0"/>
			<minDepth>0.005</minDepth>
		</gazebo>

		<joint name="${prefix}${pos}_${side}_wheel_joint" type="continuous">
			<parent link="$(arg prefix)base_link"/>
			<child link="${prefix}${pos}_${side}_wheel"/>
			<axis xyz="0 1 0"/>
			<origin xyz="${xyz}" rpy="${rpy}"/>
			<mimic joint="${prefix}virtual_${side}_wheel_joint" multiplier="1" offset="0"/>
		</joint>

		<transmission name="${prefix}${pos}_${side}_wheel_trans" type="SimpleTransmission">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${prefix}${pos}_${side}_wheel_joint">
				<hardwareInterface>VelocityJointInterface</hardwareInterface>
			</joint>
			<actuator name="${prefix}{pos}_${side}_wheel_motor">
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission>
	</xacro:macro>


	<xacro:macro name="virtual_wheel" params="prefix side xyz">   
		<link name="${prefix}virtual_${side}_wheel">
		<visual>
			<origin xyz=".0 0 0" rpy="${PI/2} 0 0 "/>
			<geometry>
			<cylinder length="0.01" radius="${wheel_radius}"/>
			</geometry>
			<material name="invisible"/>
		</visual>
		</link>
		<joint name="${prefix}virtual_${side}_wheel_joint" type="continuous">
		<parent link="${prefix}base_footprint"/>
		<child link="${ prefix}virtual_${side}_wheel"/>
		<origin xyz="${xyz}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<limit effort="100.0" velocity="100.0"/>
		<dynamics damping="0.2"/>
		</joint>
	</xacro:macro>

	<xacro:property name="wheelbase" value="0.24" />
	<xacro:property name="wheel_radius" value="0.05" />

	<xacro:wheel prefix="$(arg prefix)" pos="rear" side="left"   xyz="-0.07525  +${wheelbase/2} -0.025" rpy="${-5*PI/180} 0 0" /> <!-- rear_left_wheel -->
	<xacro:wheel prefix="$(arg prefix)" pos="rear" side="right"  xyz="-0.07525 -${wheelbase/2} -0.025" rpy="${5*PI/180} 0 0" /> <!-- rear_right_wheel -->
	<xacro:wheel prefix="$(arg prefix)" pos="front" side="left"  xyz=" 0.07525  +${wheelbase/2} -0.025" rpy="${-5*PI/180} 0 0" /> <!-- front_left_wheel -->
	<xacro:wheel prefix="$(arg prefix)" pos="front" side="right" xyz=" 0.07525 -${wheelbase/2} -0.025" rpy="${5*PI/180} 0 0" /> <!-- front_right_wheel -->
	<xacro:virtual_wheel prefix="$(arg prefix)" side="left" xyz="0 +${wheelbase/2} ${wheel_radius}"/> <!-- virtual_left_wheel -->
	<xacro:virtual_wheel prefix="$(arg prefix)" side="right" xyz="0 -${wheelbase/2} ${wheel_radius}"/> <!-- virtual_right_wheel -->

	
	<gazebo>
		<plugin name="$(arg prefix)gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace>/</robotNamespace>
			<robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
		</plugin>

		<plugin name="$(arg prefix)imu_controller" filename="libgazebo_ros_imu.so">
			<alwaysOn>true</alwaysOn>
			<updateRate>20.0</updateRate>
			<bodyName>base_imu_link</bodyName>
			<topicName>imu</topicName>
			<gaussianNoise>0.05</gaussianNoise>
			<frameName>base_imu_link</frameName>
			<xyzOffsets>0 0 0</xyzOffsets>
			<rpyOffset>0 0 0</rpyOffset>
			<serviceName>/default_imu</serviceName>
		</plugin>
	</gazebo>

	<xacro:macro name="range_sensor" params="name ros_topic update_rate minRange maxRange fov radiation">
		<gazebo reference="${name}">
			<sensor type="ray" name="${name}_sensor">
				<pose>0 0 0 0 0 0</pose>
				<update_rate>${update_rate}</update_rate>
				<visualize>false</visualize>
				<ray>
					<scan>
						<horizontal>
							<samples>5</samples>
							<resolution>1</resolution>
							<min_angle>-${fov/2}</min_angle>
							<max_angle>${fov/2}</max_angle>
						</horizontal>
						<vertical>
							<samples>5</samples>
							<resolution>1</resolution>
							<min_angle>-${fov/2}</min_angle>
							<max_angle>${fov/2}</max_angle>
						</vertical>
					</scan>
					<range>
						<min>${minRange}</min>
						<max>${maxRange}</max>
						<resolution>0.01</resolution>
					</range>
				</ray>
				<plugin filename="libgazebo_ros_range.so" name="gazebo_ros_range">
					<gaussianNoise>0.005</gaussianNoise>
					<alwaysOn>true</alwaysOn>
					<updateRate>${update_rate}</updateRate>
					<topicName>${ros_topic}</topicName>
					<frameName>${name}</frameName>
					<fov>${fov}</fov>
					<radiation>${radiation}</radiation>
				</plugin>
			</sensor>
		</gazebo>
	</xacro:macro>

	<xacro:range_sensor name="$(arg prefix)sonar_forward_left" ros_topic="$(arg prefix)range_forward_left" update_rate="10" minRange="0.04" maxRange="0.5" fov="${20*PI/180}" radiation="ultrasound" />
	<xacro:range_sensor name="$(arg prefix)sonar_forward_right" ros_topic="$(arg prefix)range_forward_right" update_rate="10" minRange="0.04" maxRange="0.5" fov="${20*PI/180}" radiation="ultrasound" />
	<xacro:range_sensor name="$(arg prefix)sonar_backward" ros_topic="$(arg prefix)range_backward" update_rate="10" minRange="0.04" maxRange="0.5" fov="${20*PI/180}" radiation="ultrasound" />

	<gazebo reference="$(arg prefix)lidar">
		<sensor type="ray" name="$(arg prefix)head_rplidar_a2_sensor">
			<pose>0 0 0 0 0 0</pose>
			<visualize>false</visualize>
			<update_rate>12</update_rate>
			<ray>
				<scan>
					<horizontal>
						<samples>360</samples>
						<resolution>1</resolution>
						<min_angle>-3.12413907051</min_angle>
						<max_angle>3.14159274101</max_angle>
					</horizontal>
				</scan>
				<range>
					<min>0.20</min>
					<max>16.0</max>
					<resolution>0.01</resolution>
				</range>
				<noise>
					<type>gaussian</type>
					<mean>0.0</mean>
					<stddev>0.01</stddev>
				</noise>
			</ray>
			<plugin name="gazebo_ros_head_rplidar_a2_controller" filename="libgazebo_ros_laser.so">
				<topicName>/scan</topicName>
				<frameName>lidar</frameName>
			</plugin>
		</sensor>
	</gazebo>

	<!-- <xacro:include filename="gazebo_control.xacro" /> -->
	<xacro:include filename="ros2_control.xacro" />

	<xacro:modelidar_ros2_control name="Modelidar" prefix="$(arg prefix)" use_mock_hardware="$(arg use_mock_hardware)"/>

</robot>
